name: netwolf
description: Inspired by Netfox on iOS. Netwolf allows for easy debugging of network requests made in your app via the use of interceptors.
version: 0.0.1
homepage:

environment:
  sdk: ">=2.17.0 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  collection: ^1.16.0
  dio: ^4.0.6
  flutter:
    sdk: flutter
  notification_dispatcher: ^0.2.0
  shake: ^2.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  very_good_analysis: ^3.0.0

flutter:
