name: netwolf
description: Inspired by Netfox on iOS. Netwolf allows for easy debugging of network requests made in your app via the use of interceptors.
version: 0.3.0
homepage: https://github.com/pongloongyeat/netwolf

environment:
  sdk: ">=2.17.0 <3.0.0"
  flutter: ">=3.0.0"

dependencies:
  collection: ^1.17.0
  dio: ^5.1.1
  flutter:
    sdk: flutter
  notification_dispatcher:

dev_dependencies:
  flutter_test:
    sdk: flutter
  very_good_analysis: ^4.0.0

flutter:
